# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build and Test'
  steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '11'
      addToPath: true

  - task: Sbt@1
    inputs:
      sbtCommand: 'compile test'
      options: '-Dplay.server.pidfile.path=/tmp/play.pid'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'target/universal'
      artifactName: 'drop'
      publishLocation: 'Container'

